### ISSUE TITLE
JMI Sales Register Report does not include returns

### ISSUE THREAD

**Issue by bkm888** [mntechnique/jmi_erpnext#33]
The custom sales register report (JMI Sales Register) does not capture any Sales Invoices with negative grand totals (returns). This is important to helping the sales users to keep track of their sales totals for the day.

This feature work correctly in the standard Sales Register Report.

Please address this issue for us at your soonest convenient opportunity.

Thank you,
Bryan Miles
JMI Barcodes

**Comment by unmesh87** [comment]
We had a chance to go through functionality on test server for return entry issue and it seems to be reflecting correctly. 

![jmi_sales_register](https://user-images.githubusercontent.com/20383222/38768579-bc01c508-4013-11e8-80db-59efbb3ec731.png)

**Procedure to make sales return**

- Submit sales invoice.

- Find Make button to do return entry as shown below
![make_sales_return](https://user-images.githubusercontent.com/20383222/38768658-d55085c0-4014-11e8-9507-9639f4d6ce68.png)

- Select Series "Sales Return" and submit the document.

- Negative entries will reflect in Jmi_sales_register. 

**_Note_**: Access to production server is required to see if code is pushed correctly.

**Comment by bkm888** [comment]
Sudoers login credentials have been sent to your email for the production server.
The production server does not seem to work the same as the test server.

Thank you,
BKM

**Comment by saurabh-bhosale** [comment]
Closing the issue. Sales return entries are reflecting in JMI Sales Register only need to select return naming series correctly.
