### ISSUE TITLE
JMI Barcodes customized "Mobile - POS Invoice" uses wrong customer name

### ISSUE THREAD

**Issue by bkm888** [mntechnique/jmi_erpnext#47]
In production server, a customer recently sent paperwork to company requesting a names change. The customer record was updated with the new name. The old name is still used in the customer record to maintain the record integrity in ERPNext and the new name was listed in the "Customer Name" field.

When printing invoices for this customer using the customized "Mobile - POS Invoice" it appears that the "Customer" field is being used instead of the "Customer Name" field when printing. If the "Standard" print format is selected at time of printing instead of the customized format, the new customer name appears correctly at top of printed Invoice. When using the Mobile - POS Invoice the old customer appears at top of printed Invoice.

** This also appears to be true of the JMI Barcodes customized "Stationary - POS Invoice"

**Comment by ghost** [comment]
@bkm888 
You need 'Customer Name' from Customer on Mobile - POS Invoice and not the customer Id? 
Because Mobile POS Invoice was made by fetching the 'Customer ID' which is there in Sales Invoice.
Just checking if you do not need 'Customer ID' in the Mobile POS Invoice?

**This is how it will look, If we take the 'Customer Name' from customer**
![cust](https://user-images.githubusercontent.com/29235673/39188370-421dd9ac-47ed-11e8-9df6-e7eebcfe464f.png)

**Comment by bkm888** [comment]
@Siddhisawant8  No, that is incorrect. However, Thank you for pointing out another issue!

The "Customer ID" at the top of the printed invoice is supposed to be populated with the custom field that we had added to the customer record. I believe it is jmi_customer_id although I am not sure. You would have to ask @unmesh87 about what is the actual field designation. Evidently it is broken and not being populated at all. See below:

**Please ignore the difference in the letterhead. The client has checked the letterhead box.

![image](https://user-images.githubusercontent.com/30693364/39192540-631f451e-47a7-11e8-82bf-ba5bfd91d15f.png)


However if you go to the customer record and look, you will see the following information that is supposed to be used to populate that area of the printed Sales Invoice. Below I have attached 2 screen shots of the Customer record that brought the initial error into view. When the original customer information was imported to ERPNExt the Customer and Customer Name were the same. The areas circled in red indicate the Original ERPNext Customer ID (called "Customer" in the import template) in the upper right corner, the new Customer Name in the name field and the Added Customer ID that we use as a key field to tie the record to an external accounting program. This field is at the very bottom of the customer record.

![image](https://user-images.githubusercontent.com/30693364/39191483-06d8ee7e-47a5-11e8-8ddc-18f639a5d6df.png)

![image](https://user-images.githubusercontent.com/30693364/39191695-841a1d4a-47a5-11e8-8992-9a57f6f003c6.png)


So, to make this a little clearer. If you were to create a new Sales Invoice using the ERPNext customer "PERFORMANCE FORD" the following Sales Invoice fields should be populated this way:

Bill to Customer: "FELIX SEBATES FORD"   (ship to name should match)
Customer ID:  "PERFO"

On the production server (thanks to your pointing it out) there are now 2 issues with the print format.
1st issue, the customer name is not correct. It would currently read "PERFORMANCE FORD" even though the name had been changed in the customer record.
2nd issue, the Customer ID is not being populated at all. It should read "PERFO" 

Please let me know if there is not enough information here. I want to make sure you understand what I am trying to point out as issues.

Thank you.
BKM

**Comment by unmesh87** [comment]
@bkm888 thanks for pointing issue in detail. 

@Siddhisawant8 , 

Test case locally by renaming customer to see all details are pulled correctly in sales invoices.

**Comment by ghost** [comment]
@bkm888 
I have tried your test cases locally, and made few changes also. 

**Renaming an existing customer :** 
![edited_jmi](https://user-images.githubusercontent.com/29235673/39245474-8be92892-48b1-11e8-9fd3-fb804500dd60.png)

**Customer ID on customer:** 
![edited_jmi_3](https://user-images.githubusercontent.com/29235673/39245478-8c9258fe-48b1-11e8-93f7-297253bfc8c3.png)

**Now in the the existing Sales Invoice of that same customer**
**-  New customer name is fetched.**
**-  Customer ID (jmi_customer_id) is fetched.**
![edited_jmi_2](https://user-images.githubusercontent.com/29235673/39245476-8c446856-48b1-11e8-929e-9974d064659e.png)

**Comment by bkm888** [comment]
@Siddhisawant8  - Thank you! that looks exactly as I would expect. You are part of a great team.
@unmesh87  - Thank you  (on many cases). I look forward to hear from you when it is ready to test on the GCP test server.

BKM

**Comment by ghost** [comment]
@bkm888 

Latest fixes of raised Github issues are up on the new test server.
