### ISSUE TITLE
Daily Sales Invoice report - G/L Account information has disappeared.

### ISSUE THREAD

**Issue by bkm888** [mntechnique/jmi_erpnext#50]
In the earlier version of this report the column was being properly filled with the 2 account numbers for items sold and taxes. Please put this back to the way is was before the last set of changes.

If this is the result of the changes to the "Accounts Receivable Account" column, then the solution designed for that column will not work for the G/L Account column. The G/L column uses only 2 account numbers. One for all items and services sold, and another for all taxes regardless of type or jurisdiction. ERPNext would not allow every individual county and state tax to have the exact same account number.

Where the Accounts Receivable Account column is always the same (Deptors - MSD) account so the number can be applied in the chart of accounts. The same is not true for all the different sales taxes.

Please look into this again.

**Comment by ghost** [comment]
@bkm888 

Yes, system validates correctly when same account number is entered for different ledger. 

Instead of hard-coding the value we are thinking of creating a 'Settings' page for update friendly approach to avoid lengthy procedure of implementing and pushing data again to production server.

**Comment by ghost** [comment]
@bkm888 
Here is how we can take G/L account data in the report:


- Sales and services belong to same parent account
- All the taxes have the same parent account
We suggest you to assign those account numbers (If product set to “40200” and if tax set value to “23100”) to the 'Parent Account' of those accounts.
Here I have done the same here, by replicating some of your accounts locally.
![local_acc](https://user-images.githubusercontent.com/29235673/39633971-218fdc16-4fd7-11e8-84ea-74b56414cb5a.png)

It gives the same result, instead of hard-coding:
![acc_rec](https://user-images.githubusercontent.com/29235673/39633963-1c2716a4-4fd7-11e8-8bb4-7b5944231afb.png)

Also, We have pushed the latest changes on the gcp test server.
If you approve this approach we will push these changes also.

**Comment by bkm888** [comment]
Siddhi,
 
( I do not know if responding to the emails sent from github will find their way to you so I have copied Unmesh directly just in case. So, her could forward to you if it was not received.)
 
I have attempted to run this very test on the GCP test server and the G/L Account column still comes out empty.
 
I have attached a excel file that I exported form the report and a screenshot of the modified "Chart of Accounts". The excel file uses data from 4-4-2018 because the test server only has old data. I cannot restore a fresh set of data to it because it will destroy the other modifications we are also testing.
 

 
 
You will be able to see in the Chart of Accounts I have modified the parent accounts of the 3 required account heads and in the report running on the GCP Test Server (35.231.61.5) only the "Accounts Receivable" column seems to populate correctly. The "G/L Account" remains blank.
 
I can only think of very few things that might be wrong in my test:
 
- Maybe you have not updated the GCP test server with your fixes?
 
- Maybe it only works on NEW records? (but then why does the Accnt Rec column work in retrospect?)
 
- Maybe it really doesn't work with parent accounts?
 
Please run this yourself on the GCP test server and let me know if I have something wrong.
 
Bryan Miles
JMI Barcodes
bkm@jmibarcodes.com
 
-----Original Message-----

**Comment by ghost** [comment]
@bkm888 
This particular change was not pushed on the test gcp, If this functional approach is acceptable by you we will push them up on test gcp by EOD.

**Comment by bkm888** [comment]
Siddhi,
 
While this was not my first choice for a solution, it certainly seems to be the most logical way to approach the issue. So, please do move the solution to the test server for further testing.
 
Thank you for expanding your thinking to come up with this alternative.
 
Bryan Miles
JMI Barcodes
bkm@jmibarcodes.com
 
 
-----Original Message-----

**Comment by ghost** [comment]
@bkm888 we have pushed this functionality on the test server. 
Do let us know if there is anything that still needs attention. 

Also, I suggest we can use the same approach for 'Accounts receivable' column. 
That way, we can have all the Accounts related columns update-friendly.
(On the test server, I have made required changes for 'Accounts Receivable' column, please check and do let me know if any clarity is required.)

**Comment by bkm888** [comment]
Siddhi,
 
Thank you!!
 
Initial testing of the changes on the GCP test server appear to be working as expected. I will visit the clinet site and try it there from the test
server and make sure the results match with their expectations.
 
The only thing left at this point that must be done before I can deliver it to my client is the filtering requested in GitHub issue #43
 
https://github.com/mntechnique/jmi_erpnext/issues/43
 
Once that is ready, I can complete the final testing and allow for delivery.
 
Thank you again. So far this is looking good.
 
Bryan Miles
JMI Barcodes
bkm@jmibarcodes.com
 
 
-----Original Message-----
