### ISSUE TITLE
Mobile - POS Invoice -- Customer name not correct (ref Issue #47 & #53)

### ISSUE THREAD

**Issue by bkm888** [mntechnique/jmi_erpnext#57]
Reference:
"In Issue #47 I described a problem with how the Customer Name was populated on the printed Sales Invoice. The issue was closed but it was only partially fixed."

I have been attempting to test the revisions that were made to resolve this issue and it appears to still be incorrect as described in issue #53

Have these revisions been sent up to the testing server?

**Comment by ghost** [comment]
@bkm888 those changes we haven't pushed on your test server yet. We will have them up by today.

**Comment by ghost** [comment]
@bkm888 We have updated the gcp test server.
As discussed earlier, SINV-00021 explained your issue. 
Please check the same invoice for the solution.
