### ISSUE TITLE
Stationary - POS Invoice -- Customer name not correct (ref Issue #47) 

### ISSUE THREAD

**Issue by bkm888** [mntechnique/jmi_erpnext#59]
Siddhi and Unmesh,

Could you please take the same fix you applied to our Mobile - POS Invoice for getting the changed customer name correct, and apply the same fix to the Stationary - POS Invoice. We want to be uniform across our printed receipts with customers.

Here is a screen shot of the (now fixed) Mobile POS Invoice:
![image](https://user-images.githubusercontent.com/30693364/39703376-e0790602-51d5-11e8-9254-b8f881569baa.png)

and here is the very same invoice with the Stationary POS Invoice selected:

![image](https://user-images.githubusercontent.com/30693364/39703410-f5ca9c50-51d5-11e8-8b6b-45c33b77fd51.png)

I cannot imagine this would take any additional development time, but it will require someone to move the same code into the Stationary POS Invoice.

You have approval in advance to make this change and add the editing costs to our invoice.

Thank you BOTH for such great work!

Bryan Miles
JMI Barcodes

**Comment by ghost** [comment]
@bkm888 
This functionality is up on the gcp test server. 
Invoice MS9-100788 is referred to replicate your case.

**Comment by bkm888** [comment]
Siddhi, Unmesh and Dev team,
 
All of the recent changes to the "Mobile - POS Invoice" and the "Stationary - POS Invoice" in the multiple github issues against those two functions have now been tested on the GCP Test Server and we believe them to be fully functional.
 
Can you please now move these changes to the live production server ( 173.214.175.140 ) and have Nihar prepare my invoice. If you prefer wait and place it all on one invoice, that will be fine as well.
 
All of your previous login credentials for the live production server are still valid.
 
We look forward to hearing more from you today on the progress on the last two remaining githib issues.
 
Thank you,
 
Bryan Miles
JMI Barcodes
bkm@jmibarcodes.com
 
 
 
-----Original Message-----
