### ISSUE TITLE
Mobile - POS Invoice - Discount Amount and Total Amount not correct

### ISSUE THREAD

**Issue by bkm888** [mntechnique/jmi_erpnext#60]
In the new "modified" version of the Mobile POS Invoice, after the "Discount Amount" was added to the Invoice it is not displaying correctly. 

If a sales invoice has a discount applied, everything works correctly.
If a sales invoice does not have a discount applied, the Total Amount appears in the Discount line.

Here is a sales invoice that has a discount applied:
![image](https://user-images.githubusercontent.com/30693364/39703957-e897d0be-51d7-11e8-9f70-b9e967846aac.png)

And here is another sales invoice for the same customer that does NOT have a discount:
![image](https://user-images.githubusercontent.com/30693364/39703975-ff67040e-51d7-11e8-8325-6b009bcabc38.png)

**Comment by ghost** [comment]
@bkm888  this minor change is fixed, please check.

**Comment by bkm888** [comment]
Has the change been moved to the GCP test server?
 
BKM
 
 
-----Original Message-----

**Comment by ghost** [comment]
@bkm888 Yes.
