### ISSUE TITLE
CSV File Generator no longer working

### ISSUE THREAD

**Issue by bkm888** [mntechnique/jmi_erpnext#78]
There is an excerpt below from an email exchange with @unmesh87 about the CSV file generator the dev team make for us. I would like to be able to resume testing this. Is is possible to get the links fixed?

Email:
As of now CSV files will auto download with the help of links listed below after updating item master detail (barcodes, item code and description). You can check response by pasting links in browser-

Barcode : http://jmibarcodes.mntechnique.com/files/ProductCodes_barcode.csv
Item code : http://jmibarcodes.mntechnique.com/files/ProductCodes_itemcode.csv
Description : http://jmibarcodes.mntechnique.com/files/ProductCodes_description.csv

Note : On editing information each time, use above links to download fresh data. 

We can build an app to have better control of csv generation on demand once format is acceptable. Disabled items still show up in the list, this is something we will have to work over(if it needs to be fixed.)

You can directly raise issues on our Github repo.

**Comment by unmesh87** [comment]
@saurabh-bhosale and @gaurav-naik check GCP server and make CSV files for Barcode, Itemcode and Description available for user testing.

**Comment by unmesh87** [comment]
@bkm888 

Following links are available for testing on GCP server-

> Barcode : http://jmibarcodes.mntechnique.com/files/ProductCodes_barcode.csv
Item code : http://jmibarcodes.mntechnique.com/files/ProductCodes_itemcode.csv
Description : http://jmibarcodes.mntechnique.com/files/ProductCodes_description.csv

E.g to download **Item code** CSV file use- 

- GCP IP address/files/ProductCodes_itemcode.csv 

- Open link in browser tab

-   Remove **http or https** (00.99.123.12/files/ProductCodes_itemcode.csv)

- File will download automatically with item code as first column. 

- Repeat to download for all CSV files.

**Comment by bkm888** [comment]
This function has been tested and is working well for us. We have found a way to use the files in their default location. This means no further application code is needed.

Please move the current code to my live production server as soon as possible and let me know when it is there. Thank you.

BKM

**Comment by unmesh87** [comment]
@bkm888 

Please move the current code to my live production server as soon as possible and let me know when it is there. Thank you

> CSV file export is available on production server as well. You can download files by;  
                 domain name/files/ProductCodes_itemcode.csv. 

Cheers.
